name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    name: Install sanity check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies
        uses: semabit/gh-workflows/.github/actions/yarn-install@v1
